# Generated by Django 5.1 on 2026-05-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('inventory_number', models.CharField(help_text='Пятизначный инвентарный номер (например: 00001, 12345)', max_length=5, unique=True, verbose_name='Инвентарный номер')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Издательство')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Автор'), ('compiler', 'Составитель'), ('editor', 'Редактор'), ('translator', 'Переводчик'), ('illustrator', 'Иллюстратор')], default='author', max_length=50, verbose_name='Роль')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author', verbose_name='Автор')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Связь книга-автор',
                'verbose_name_plural': 'Связи книга-автор',
                'unique_together': {('book', 'author', 'role')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='app.BookAuthor', to='app.author'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название произведения')),
                ('original_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Оригинальное название')),
                ('work_type', models.CharField(choices=[('story', 'Рассказ'), ('poem', 'Стихотворение'), ('article', 'Статья'), ('chapter', 'Глава'), ('excerpt', 'Отрывок'), ('novella', 'Повесть'), ('essay', 'Эссе'), ('play', 'Пьеса'), ('other', 'Другое')], default='story', max_length=50, verbose_name='Тип произведения')),
                ('first_page', models.IntegerField(blank=True, null=True, verbose_name='Страница начала')),
                ('last_page', models.IntegerField(blank=True, null=True, verbose_name='Страница конца')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое содержание')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Год первой публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.author', verbose_name='Автор произведения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.book', verbose_name='Сборник')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ['book', 'first_page', 'title'],
            },
        ),
    ]
