# Generated by Django 5.1 on 2026-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('novel', 'Роман'), ('story', 'Рассказ'), ('novella', 'Повесть'), ('short_story', 'Новелла'), ('essay', 'Эссе'), ('feuilleton', 'Фельетон'), ('sketch', 'Очерк'), ('parable', 'Притча'), ('fairy_tale', 'Сказка'), ('myth', 'Миф'), ('legend', 'Легенда'), ('fable', 'Басня'), ('poem', 'Стихотворение'), ('verse', 'Стих'), ('ballad', 'Баллада'), ('ode', 'Ода'), ('elegy', 'Элегия'), ('sonnet', 'Сонет'), ('epigram', 'Эпиграмма'), ('haiku', 'Хайку'), ('lyrics', 'Лирика'), ('epic_poem', 'Поэма'), ('rhyme', 'Рифмовка'), ('play', 'Пьеса'), ('tragedy', 'Трагедия'), ('comedy', 'Комедия'), ('drama', 'Драма'), ('tragicomedy', 'Трагикомедия'), ('monologue', 'Монолог'), ('skit', 'Сценка'), ('script', 'Сценарий'), ('article', 'Статья'), ('reportage', 'Репортаж'), ('interview', 'Интервью'), ('review', 'Рецензия'), ('critique', 'Критика'), ('column', 'Колонка'), ('public_letter', 'Публичное письмо'), ('memoirs', 'Мемуары'), ('biography', 'Биография'), ('autobiography', 'Автобиография'), ('diary', 'Дневник'), ('letter', 'Письмо'), ('speech', 'Речь'), ('scientific_article', 'Научная статья'), ('monograph', 'Монография'), ('textbook', 'Учебник'), ('tutorial', 'Учебное пособие'), ('methodical', 'Методичка'), ('thesis', 'Диссертация'), ('abstract', 'Тезисы'), ('lecture', 'Лекция'), ('research', 'Исследование'), ('dictionary_entry', 'Словарная статья'), ('encyclopedia', 'Энциклопедическая статья'), ('commentary', 'Комментарий'), ('children_poem', 'Детское стихотворение'), ('lullaby', 'Колыбельная'), ('nursery_rhyme', 'Потешка'), ('pestushka', 'Пестушка'), ('counting_rhyme', 'Считалка'), ('tongue_twister', 'Скороговорка'), ('riddle', 'Загадка'), ('bedtime_story', 'Сказка на ночь'), ('educational_story', 'Познавательный рассказ'), ('folk_tale', 'Народная сказка'), ('epic', 'Былина'), ('historical_song', 'Историческая песня'), ('ritual_poetry', 'Обрядовая поэзия'), ('proverb', 'Пословица'), ('saying', 'Поговорка'), ('chant', 'Закличка'), ('folklore', 'Фольклор'), ('prayer', 'Молитва'), ('sermon', 'Проповедь'), ('parable_religious', 'Притча религиозная'), ('hagiography', 'Житие'), ('psalm', 'Псалом'), ('canon', 'Канон'), ('epistle', 'Послание'), ('open_letter', 'Открытое письмо'), ('dedication', 'Посвящение'), ('epigraph', 'Эпиграф'), ('aphorism', 'Афоризм'), ('quote', 'Цитата'), ('maxim', 'Максима'), ('thought', 'Мысль'), ('reflection', 'Размышление'), ('note', 'Заметка'), ('fragment', 'Фрагмент'), ('excerpt', 'Отрывок'), ('prologue', 'Пролог'), ('epilogue', 'Эпилог'), ('foreword', 'Предисловие'), ('afterword', 'Послесловие'), ('introduction', 'Введение'), ('conclusion', 'Заключение'), ('appendix', 'Приложение'), ('glossary', 'Глоссарий'), ('chapter', 'Глава'), ('part', 'Часть'), ('volume', 'Том'), ('section', 'Раздел'), ('other', 'Другое'), ('mixed', 'Смешанный жанр'), ('unknown', 'Не определено')], default='fairy_tale', max_length=50, verbose_name='Тип произведения'),
        ),
    ]
