# Generated by Django 6.0.7 on 2026-07-19 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_work_work_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name': 'Автор книги', 'verbose_name_plural': 'Авторы книг'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['title'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, default='', verbose_name='Биография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Издательство'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='app.author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='app.book'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='role',
            field=models.CharField(choices=[('author', 'Автор'), ('compiler', 'Составитель'), ('editor', 'Редактор'), ('translator', 'Переводчик')], default='author', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.author'),
        ),
        migrations.AlterField(
            model_name='work',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.book'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое содержание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Оригинальное название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('novel', 'Роман'), ('story', 'Рассказ'), ('novella', 'Повесть'), ('short_story', 'Новелла'), ('poem', 'Стихотворение'), ('ballad', 'Баллада'), ('fairy_tale', 'Сказка'), ('play', 'Пьеса'), ('article', 'Статья'), ('essay', 'Эссе'), ('memoirs', 'Мемуары'), ('biography', 'Биография'), ('chapter', 'Глава'), ('excerpt', 'Отрывок'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип произведения'),
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='Рейтинг от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('review', models.TextField(blank=True, help_text='Ваша рецензия на книгу', verbose_name='Рецензия')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная книга',
                'verbose_name_plural': 'Избранные книги',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
