# Generated by Django 5.1.2 on 2026-08-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_options_alter_bookauthor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('favorites', models.IntegerField(default=0, verbose_name='Добавления в избранное')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app.book')),
            ],
            options={
                'verbose_name': 'Статистика книги',
                'verbose_name_plural': 'Статистика книг',
                'ordering': ['-date'],
                'unique_together': {('book', 'date')},
            },
        ),
    ]
